name: Fork PR Processor

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to process (e.g., 670)'
        required: true
      fork_branch:
        description: 'Branch name in the fork repository (e.g., talesoftibia-gh:patch-29)'
        required: true

jobs:
  process_fork_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Extract fork owner and branch
        id: extract_info
        run: |
          FORK_OWNER=$(echo "${{ github.event.inputs.fork_branch }}" | cut -d':' -f1)
          BRANCH_NAME=$(echo "${{ github.event.inputs.fork_branch }}" | cut -d':' -f2)
          echo "fork_owner=$FORK_OWNER" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Fetch and merge fork branch
        env:
          FORK_OWNER: ${{ steps.extract_info.outputs.fork_owner }}
          BRANCH_NAME: ${{ steps.extract_info.outputs.branch_name }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
        run: |
          git remote add fork https://github.com/$FORK_OWNER/tibia.git
          git fetch fork $BRANCH_NAME
          git checkout -b process-fork-pr-$PR_NUMBER
          git merge --no-ff fork/$BRANCH_NAME -m "Merge changes from fork PR #$PR_NUMBER by @$FORK_OWNER"
          if [ $? -ne 0 ]; then
            echo "Merge conflict occurred. Manual intervention required."
            git merge --abort
            exit 1
          fi

      - name: Push changes
        run: |
          git push origin process-fork-pr-${{ github.event.inputs.pr_number }}

      - name: Create or update PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          FORK_OWNER: ${{ steps.extract_info.outputs.fork_owner }}
        run: |
          PR_BRANCH="process-fork-pr-$PR_NUMBER"
          
          PR_INFO=$(gh pr view $PR_NUMBER --json title,body,author)
          PR_TITLE=$(echo $PR_INFO | jq -r .title)
          PR_BODY=$(echo $PR_INFO | jq -r .body)
          PR_AUTHOR=$(echo $PR_INFO | jq -r .author.login)
          
          EXISTING_PR=$(gh pr list --head $PR_BRANCH --json number --jq '.[0].number')
          
          PR_BODY_WITH_CREDIT="This PR processes changes from fork PR #$PR_NUMBER by @$PR_AUTHOR.

          Original PR description:
          $PR_BODY

          Thank you for your contributions @$PR_AUTHOR!
          Wait for a maintainer to apply changes with the /apply comment command."
          
          if [ -z "$EXISTING_PR" ]; then
            NEW_PR=$(gh pr create --base main --head $PR_BRANCH \
              --title "$PR_TITLE" \
              --body "$PR_BODY_WITH_CREDIT")
            if [ $? -ne 0 ]; then
              echo "Failed to create PR. There might be no changes to commit."
              exit 1
            fi
            echo "new_pr=$NEW_PR" >> $GITHUB_OUTPUT
          else
            gh pr edit $EXISTING_PR --title "$PR_TITLE" \
              --body "$PR_BODY_WITH_CREDIT"
            echo "new_pr=$EXISTING_PR" >> $GITHUB_OUTPUT
          fi

      - name: Comment and close original PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          FORK_OWNER: ${{ steps.extract_info.outputs.fork_owner }}
          NEW_PR: ${{ steps.create_or_update_pr.outputs.new_pr }}
        run: |
          CLOSING_COMMENT="Thank you for your contribution! Your changes have been processed and are now being handled in PR #$NEW_PR.

          We greatly appreciate your effort to improve our project. Your original PR is being closed to streamline our workflow, but your contributions are valued and will be reviewed in the new PR.

          If you have any questions or would like to make additional changes, please feel free to comment on the new PR #$NEW_PR.

          Thank you again for your support and involvement in our project!"

          gh pr comment $PR_NUMBER --body "$CLOSING_COMMENT"
          gh pr close $PR_NUMBER --comment "Closed in favor of PR #$NEW_PR"

      - name: Comment on new PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          FORK_OWNER: ${{ steps.extract_info.outputs.fork_owner }}
          NEW_PR: ${{ steps.create_or_update_pr.outputs.new_pr }}
        run: |
          PR_INFO=$(gh pr view $PR_NUMBER --json author)
          PR_AUTHOR=$(echo $PR_INFO | jq -r .author.login)
          gh pr comment $NEW_PR --body "This PR processes changes from fork PR #$PR_NUMBER. Original contributor: @$PR_AUTHOR. Thank you for your contributions!"
