name: Fork PR Processor

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number of the fork PR to process'
        required: true
      fork_owner:
        description: 'Owner of the fork repository'
        required: true
      fork_branch:
        description: 'Branch name in the fork repository'
        required: true

jobs:
  process_fork_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Fetch and merge fork branch
        env:
          FORK_OWNER: ${{ github.event.inputs.fork_owner }}
          FORK_BRANCH: ${{ github.event.inputs.fork_branch }}
        run: |
          git remote add fork https://github.com/$FORK_OWNER/tibia.git
          git fetch fork $FORK_BRANCH
          git checkout -b process-fork-pr-${{ github.event.inputs.issue_number }}
          git merge fork/$FORK_BRANCH --no-commit --no-ff

      - name: Create or update PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
        run: |
          PR_BRANCH="process-fork-pr-$ISSUE_NUMBER"
          git push origin $PR_BRANCH
          
          ISSUE_INFO=$(gh issue view $ISSUE_NUMBER --json title,body)
          ISSUE_TITLE=$(echo $ISSUE_INFO | jq -r .title)
          ISSUE_BODY=$(echo $ISSUE_INFO | jq -r .body)
          
          EXISTING_PR=$(gh pr list --head $PR_BRANCH --json number --jq '.[0].number')
          
          if [ -z "$EXISTING_PR" ]; then
            gh pr create --base main --head $PR_BRANCH \
              --title "Process fork PR #$ISSUE_NUMBER: $ISSUE_TITLE" \
              --body "This PR processes changes from fork PR #$ISSUE_NUMBER.

              Original PR description:
              $ISSUE_BODY

              Apply changes with /apply command."
          else
            gh pr edit $EXISTING_PR --title "Process fork PR #$ISSUE_NUMBER: $ISSUE_TITLE" \
              --body "This PR processes changes from fork PR #$ISSUE_NUMBER.

              Original PR description:
              $ISSUE_BODY

              Apply changes with /apply command."
          fi

      - name: Comment on original issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
        run: |
          PROCESS_PR=$(gh pr list --head process-fork-pr-$ISSUE_NUMBER --json number --jq '.[0].number')
          gh issue comment $ISSUE_NUMBER --body "Changes from this fork PR are being processed in PR #$PROCESS_PR. Please use the /apply command on the new PR to finalize updates."
