name: Fork PR Preparation
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  prepare_fork_pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate token
        id: generate_token
        run: echo "token=${{ secrets.TIBIA_REPOSITORY_PR_KEY }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ steps.generate_token.outputs.token }}
      
      - name: Fetch base branch
        run: |
          git remote add base https://github.com/${{ github.repository }}
          git fetch base ${{ github.base_ref }}
      
      - name: Create new branch
        run: |
          git checkout -b fork-pr-${{ github.event.pull_request.number }} base/${{ github.base_ref }}
      
      - name: Get original committer info
        id: get_committer_info
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an' ${{ github.event.pull_request.head.sha }})
          COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae' ${{ github.event.pull_request.head.sha }})
          echo "committer_name=${COMMITTER_NAME}" >> $GITHUB_OUTPUT
          echo "committer_email=${COMMITTER_EMAIL}" >> $GITHUB_OUTPUT
      
      - name: Set git identity
        run: |
          git config user.name "${{ steps.get_committer_info.outputs.committer_name }}"
          git config user.email "${{ steps.get_committer_info.outputs.committer_email }}"
      
      - name: Apply PR changes
        run: |
          if ! git merge --no-commit --no-ff --signoff ${{ github.event.pull_request.head.sha }}; then
            echo "Merge failed. There might be conflicts."
            git merge --abort
            exit 1
          fi
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code --staged || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }})
          git commit -m "$COMMIT_MSG" --signoff

      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push https://${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git fork-pr-${{ github.event.pull_request.number }}

      - name: Log branch information
        run: |
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "SHA: ${{ github.sha }}"
          echo "Branch: fork-pr-${{ github.event.pull_request.number }}"
          echo "Base ref: ${{ github.base_ref }}"

      - name: Create PR to main
        id: create_pr
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: 'Creating a PR from fork PR #${{ github.event.pull_request.number }}'
          branch: fork-pr-${{ github.event.pull_request.number }}
          base: ${{ github.base_ref }}
          title: 'NPC updates for fork PR #${{ github.event.pull_request.number }}'
          body: 'This PR contains NPC updates from the fork PR #${{ github.event.pull_request.number }}. Apply changes with `/apply` command.'

      - name: Comment on original PR
        if: steps.create_pr.outputs.pull-request-number
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: 'A new PR #${{ steps.create_pr.outputs.pull-request-number }} has been created to handle NPC updates from this fork. Please use the `/apply` command on the new PR to process updates.'
            })
