name: Fork PR Preparation
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prepare_fork_pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout s2ward/tibia repository
        uses: actions/checkout@v4
        with:
          repository: s2ward/tibia
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Fetch fork branch
        run: |
          git remote add fork https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
          git fetch fork ${{ github.event.pull_request.head.ref }}

      - name: Configure Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Create new branch with fork changes
        run: |
          git checkout -b merge-fork-${{ github.event.pull_request.number }}
          git merge --no-ff fork/${{ github.event.pull_request.head.ref }} -m "Merge fork PR #${{ github.event.pull_request.number }}"

      - name: Push new branch to s2ward/tibia
        run: |
          git push origin merge-fork-${{ github.event.pull_request.number }}

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.TIBIA_REPOSITORY_PR_KEY }}
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: Create PR to main
        env:
          GITHUB_TOKEN: ${{ secrets.TIBIA_REPOSITORY_PR_KEY }}
        run: |
          gh pr create --repo s2ward/tibia \
            --head merge-fork-${{ github.event.pull_request.number }} \
            --base main \
            --title "Merge changes from fork PR #${{ github.event.pull_request.number }}" \
            --body "This PR contains merged changes from the fork PR #${{ github.event.pull_request.number }}. Apply changes with /apply command."

      - name: Comment on original PR
        env:
          GITHUB_TOKEN: ${{ secrets.TIBIA_REPOSITORY_PR_KEY }}
        run: |
          pr_number=$(gh pr list --repo s2ward/tibia --head merge-fork-${{ github.event.pull_request.number }} --json number --jq '.[0].number')
          gh pr comment ${{ github.event.pull_request.number }} --body "A new PR #$pr_number has been created to merge updates from this fork. Please use the /apply command on the new PR to process updates."
