name: Deploy Resources
on:
  push:
    branches: [main]
    paths: ['images/**', 'data/**', 'docs/**'] # docs for testing purposes
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 10  # Fetch all history for all branches and tags

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        curl https://rclone.org/install.sh | sudo bash

    - name: Process and copy files
      run: |
        # Minimize JSON files
        for file in data/{npcs,books,status}/*.json; do
          jq -c . "$file" > "${file%.json}.min.json"
        done
        
        # Prepare directories
        mkdir -p gh-pages/{images/{books,creatures,spells,npcs},data/{npcs,books,status}}
        
        # Copy only changed image files
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^images/' | xargs -I {} cp --parents {} gh-pages/
        
        # Copy and rename minimized JSON files
        for file in data/{npcs,books,status}/*.min.json; do
          cp "$file" "gh-pages/${file%.min.json}.json"
        done

    - name: Sync to Cloudflare R2
      env:
        RCLONE_CONFIG_CLOUDFLARE_TYPE: s3
        RCLONE_CONFIG_CLOUDFLARE_PROVIDER: Cloudflare
        RCLONE_CONFIG_CLOUDFLARE_ENV_AUTH: true
        RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
        RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
        RCLONE_CONFIG_CLOUDFLARE_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
      run: |
        # Get list of changed files
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(images|data)/')
        echo "$CHANGED_FILES" > changed_files.txt

        rclone sync --files-from changed_files.txt gh-pages/ cloudflare:resources
        rm changed_files.txt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './gh-pages'
        publish_branch: gh-pages
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
