name: Publish data workflow

on:
  push:
    branches: [main]
    paths:
      - 'img/**'
      - 'api/**'
      - 'doc/**'
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: 'main'

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Install jq and rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        curl https://rclone.org/install.sh | sudo bash

    - name: Minimize JSON files
      run: |
        jq -c . main/api/conversations.json > main/api/min_conversations.json
        jq -c . main/api/npc_data.json > main/api/min_npc_data.json
        jq -c . main/api/books.json > main/api/min_books.json
        jq -c . main/api/book-images.json > main/api/min_book_images.json

    - name: Copy updated docs and minimized JSON to gh-pages branch
      run: |
        mkdir -p gh-pages/img/book
        mkdir -p gh-pages/img/creature
        mkdir -p gh-pages/img/spell
        mkdir -p gh-pages/api/tree
        cp main/img/npc/* gh-pages/img/npc/
        cp main/img/book/* gh-pages/img/book/
        cp main/img/creature/* gh-pages/img/creature/
        cp main/img/spell/* gh-pages/img/spell/
        cp main/doc/*_transcripts.md gh-pages/api/tree/
        cp main/api/min_conversations.json gh-pages/api/conversations.json
        cp main/api/min_npc_data.json gh-pages/api/npc_data.json
        cp main/api/min_books.json gh-pages/api/books.json
        cp main/api/min_book_images.json gh-pages/api/book_images.json

    - name: Sync minimized JSON files and images to Cloudflare R2
      env:
        RCLONE_CONFIG_CLOUDFLARE_TYPE: s3
        RCLONE_CONFIG_CLOUDFLARE_PROVIDER: Cloudflare
        RCLONE_CONFIG_CLOUDFLARE_ENV_AUTH: false
        RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
        RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
        RCLONE_CONFIG_CLOUDFLARE_ENDPOINT: https://05ce9959def8839d5f64b138313049bd.r2.cloudflarestorage.com
      run: |
        rclone copy main/api/min_conversations.json cloudflare:data/npcs/transcripts.json
        rclone copy main/api/min_npc_data.json cloudflare:data/npcs/npc-data.json
        rclone copy main/api/min_books.json cloudflare:data/books/books.json
        rclone copy main/api/min_book_images.json cloudflare:data/books/book-images.json
        rclone copy main/img/npc/ cloudflare:images/npcs/
        rclone copy main/img/book/ cloudflare:images/books/
        rclone copy main/img/spell/ cloudflare:images/spells/
        rclone copy main/img/creature/ cloudflare:images/creatures/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './gh-pages'
        publish_branch: gh-pages
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
