name: Update Project Status on PR Merge
on:
  pull_request:
    types:
      - closed
    paths:
      - 'data/npcs/text/**'

jobs:
  update_issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub requests
        sudo apt-get install jq

    - name: Read NPC Status JSON
      id: read_npc_status
      run: |
        content=$(cat data/status/npc_status.json | jq -c .)
        echo "npc_status=$content" >> $GITHUB_OUTPUT

    - name: Update issue, NPC status, and send Discord message
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: 51
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        NPC_STATUS_JSON: ${{ steps.read_npc_status.outputs.npc_status }}
      run: |
        python src/scripts/gha/update_project_status.py
