name: Optimize and Process Images

on:
  pull_request:
    paths:
      - 'images/**/*.gif'
      - 'images/**/*.webp'
      - 'images/**/*.png'
      - 'images/**/*.jpg'
      - 'images/**/*.jpeg'

env:
  IMAGE_DIR: 'images'

jobs:
  process-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: ${{ env.IMAGE_DIR }}/**/*.{gif,webp,png,jpg,jpeg}

    - name: Print changed files
      run: echo "${{ steps.changed-files.outputs.all_changed_files }}"

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y imagemagick pngquant optipng

    - name: Process changed images
      run: |
        process_image() {
          local file="$1"
          local dir=$(dirname "$file")
          local filename=$(basename -- "$file")
          local extension="${filename##*.}"
          local filename="${filename%.*}"
          local output_file="$dir/$filename.png"
          local temp_file=$(mktemp)

          echo "Processing: $file"

          convert "$file" -colorspace RGB PNG32:"$temp_file"
          
          local max_dim=$(identify -format "%[fx:max(w,h)]" "$temp_file")
          convert "$temp_file" -background none -gravity center -extent ${max_dim}x${max_dim} PNG32:"$temp_file"

          optipng -o2 -quiet "$temp_file"

          if [ ! -f "$file" ] || [ $(stat -c%s "$temp_file") -lt $(stat -c%s "$file") ]; then
            mv "$temp_file" "$output_file"
            echo "Optimized: $file -> $output_file"
          else
            rm "$temp_file"
            echo "Kept original: $file"
          fi
        }
        export -f process_image
        echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | xargs -I {} bash -c 'process_image "{}"'

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ env.IMAGE_DIR }}
        git diff --staged --quiet || (git commit -m "Optimize and process images" && 
          git push origin HEAD:${{ github.head_ref }})
