name: Optimize and Process Images

on:
  pull_request:
    paths:
      - 'images/**/*.gif'
      - 'images/**/*.webp'
      - 'images/**/*.png'
      - 'images/**/*.jpg'
      - 'images/**/*.jpeg'

env:
  IMAGE_DIR: 'images'

jobs:
  process-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: ${{ env.IMAGE_DIR }}/**/*.{gif,webp,png,jpg,jpeg}

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y imagemagick pngquant optipng

    - name: Process changed images
      run: |
        process_image() {
          local file="$1"
          local dir=$(dirname "$file")
          local filename=$(basename -- "$file")
          local extension="${filename##*.}"
          local filename="${filename%.*}"
          local output_file="$dir/$filename.png"
          local temp_file=$(mktemp)

          echo "Processing: $file"

          # Convert to PNG
          if ! convert "$file" -colorspace RGB PNG32:"$temp_file"; then
            echo "Error: Failed to convert $file to PNG"
            return 1
          fi
          
          # Get dimensions and pad to square if necessary
          local max_dim=$(identify -format "%[fx:max(w,h)]" "$temp_file")
          if ! convert "$temp_file" -background none -gravity center -extent ${max_dim}x${max_dim} PNG32:"$temp_file"; then
            echo "Error: Failed to pad $file to square"
            return 1
          fi

          # Optimize PNG
          if ! optipng -o2 -quiet "$temp_file"; then
            echo "Error: Failed to optimize $file"
            return 1
          fi

          # Verify the integrity of the processed image
          if ! identify "$temp_file" > /dev/null 2>&1; then
            echo "Error: Processed file $temp_file is not a valid image"
            return 1
          fi

          # Move the processed file only if it's smaller than the original
          if [ ! -f "$file" ] || [ $(stat -c%s "$temp_file") -lt $(stat -c%s "$file") ]; then
            mv "$temp_file" "$output_file"
            echo "Optimized: $file -> $output_file"
          else
            echo "Kept original: $file (processed version not smaller)"
            rm "$temp_file"
          fi

          # Final verification
          if ! identify "$output_file" > /dev/null 2>&1; then
            echo "Error: Final output file $output_file is not a valid image"
            return 1
          fi
        }
        export -f process_image
        echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | xargs -I {} bash -c 'process_image "{}" || echo "Failed to process {}"'

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ env.IMAGE_DIR }}
        git diff --staged --quiet || (git commit -m "Optimize and process images" && 
          git push origin HEAD:${{ github.head_ref }})
